name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-20.04

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Set Node.js version
        id: set_version
        run: echo "##[set-output name=node;]$(cat .node-version)"

      - name: Setup Node.js
        uses: actions/setup-node@v2.3.0
        with:
          node-version: "${{ steps.set_version.outputs.node }}"

      - name: Setup node modules cache
        uses: actions/cache@v2.1.6
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-modules-

      - name: Setup node modules
        run: npm install

      - name: Build
        run: npm run build
